version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
     - 8080:8080
     - 2222:2222
    volumes:
     - jenkins-data:/var/jenkins_home
     - maven-conf:/usr/share/maven3/conf
    restart: unless-stopped 

volumes:
  jenkins-data:
    driver: local
  maven-conf:
    driver: local
